db:
  image: mongo
  ports:
    - "27017:27017"

dev:
  build: .
  dockerfile: Dockerfile-dev
  env_file:
    - .env
  volumes:
    - ./app:/usr/src/app
  links:
    - db
  ports:
    # "host:container"
    - "8080:8080"
  command: /bin/bash
  stdin_open: true
  tty: true
